# Generated by Django 2.2.7 on 2019-11-09 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.IntegerField(verbose_name='lesson')),
                ('kanji_type', models.CharField(choices=[('kanji', 'Kanji'), ('primitive', 'Primitive')], max_length=15, verbose_name='kanji type')),
                ('heisig', models.IntegerField(blank=True, null=True, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('before_heisig', models.IntegerField(blank=True, null=True, verbose_name='before ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='ordering')),
                ('strokes', models.IntegerField(verbose_name='strokes')),
                ('kanji', models.CharField(blank=True, max_length=1, verbose_name='character')),
                ('keyword_sv', models.CharField(max_length=63, verbose_name='meaning (Swedish)')),
                ('keyword_en', models.CharField(max_length=63, verbose_name='meaning (English)')),
                ('story_sv', models.TextField(blank=True, verbose_name='story (Swedish)')),
                ('story_en', models.TextField(blank=True, verbose_name='story (English)')),
                ('kanjidic', models.CharField(blank=True, max_length=255, null=True, verbose_name='kanjidic definition')),
                ('flagged', models.BooleanField(verbose_name='flagged')),
                ('published', models.BooleanField(verbose_name='published')),
                ('parts', models.ManyToManyField(blank=True, related_name='children', to='kanjikeys.Kanji', verbose_name='parts')),
            ],
            options={
                'verbose_name': 'character',
                'verbose_name_plural': 'characters',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_from', models.IntegerField(blank=True, verbose_name='from lesson')),
                ('lesson_to', models.IntegerField(blank=True, verbose_name='to lesson')),
                ('stat_color', models.CharField(max_length=15, verbose_name='statistics colour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('success', models.BooleanField()),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanjikeys.Kanji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv', models.CharField(max_length=63)),
                ('en', models.CharField(max_length=63)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanjikeys.Kanji')),
            ],
            options={
                'verbose_name': 'meaning',
                'verbose_name_plural': 'meanings',
            },
        ),
    ]
